### ISSUE TITLE
bug: Toploader loads endlessly on CMD + click

### ISSUE THREAD

**Issue by tomcru** [gokulkrishh/expense.fyi#100]
Toploader should not trigger on CMD + click or when clicking on external links.

I can PR this issue, I would replace the current package with a drop-in replacement & a much more up-to-date library: [Holy Loader](https://github.com/tomcru/holy-loader) (this is my library) - keeping the original look 1:1, but removing the bugs.

**Comment by gokulkrishh** [comment]
> Toploader should not trigger on CMD + click or when clicking on external links.

@tomcru Now that you mentioned it, I just noticed it 😅.

> I can PR this issue, I would replace the current package with a drop-in replacement & a much more up-to-date library: [Holy Loader](https://github.com/tomcru/holy-loader) (this is my library) - keeping the original look 1:1, but removing the bugs.

Yep, thats would be great.
