### ISSUE TITLE
Site doesnt work locally :/

### ISSUE THREAD

**Issue by Aaditya-T** [gokulkrishh/expense.fyi#110]
So am trying to run the site locally, i have set all env variables except these ones:
<img width="360" alt="image" src="https://github.com/gokulkrishh/expense.fyi/assets/70804657/6a22c5c1-6b1f-4a80-b1c7-e9f9da2e7764">

and i have set the public url to `http://app.localhost:3000` (i have tried setting it to localhost:3000 as well)

and whenever i try to signup, it just keeps me at homepage instead of logging into the dashboard. I manually added my email to the db and when i try signing in, then also it just keeps me at homepage, why?

One pattern i noticed is that while signing up for official expenses.fyi - it redirects to `app.expenses.fyi` meanwhile my local link had a redirect to `loccalhost:3000` (in the magic link sent in email).

**Comment by gokulkrishh** [comment]
@Aaditya-T Oh i see, make you sure you have set the URL config in supabase for app.localhost:3000. Here is screenshot for reference.

<img width="1283" alt="Screenshot 2024-04-07 at 8 44 45 AM" src="https://github.com/gokulkrishh/expense.fyi/assets/2944237/13d3601b-4f94-4315-8d66-ab84de187450">

**Comment by Aaditya-T** [comment]
<img width="1229" alt="image" src="https://github.com/gokulkrishh/expense.fyi/assets/70804657/f9a00fe2-3101-4804-82eb-e109d7c271c5">
<img width="936" alt="image" src="https://github.com/gokulkrishh/expense.fyi/assets/70804657/974c76ae-bafc-48be-85ff-032e0aed6045">


I configured the urls but it still just keeps me on the homepage after i click the link from the email, supabase also shows the requests as completed in logs - but no token is being set in my cookies or anything
<img width="936" alt="image" src="https://github.com/gokulkrishh/expense.fyi/assets/70804657/2aef184a-5412-4ce4-bc2f-e9f08ddc5cb4">

**Comment by Aaditya-T** [comment]
Thank you! it works now 🎉
