### ISSUE TITLE
README License section - "find it here"  link redirects to "404"

### ISSUE THREAD

**Issue by Rajakumardev** [gokulkrishh/expense.fyi#3]
## Problem
README License section - "find it here"  link redirects to "404"
- Right now it redirects to [here](https://github.com/gokulkrishh/expense.fyi/blob/main/LICENSE.md)

## Expected
"find it here" Link should redirect to the proper License file.
- I think it should redirect to [here](https://github.com/gokulkrishh/expense.fyi/blob/main/LICENSE)

**Comment by gokulkrishh** [comment]
@Rajakumardev Thanks for logging an issue, this is fixed by #2
