### ISSUE TITLE
Explain how to run `app.localhost:3000`

### ISSUE THREAD

**Issue by perryraskin** [gokulkrishh/expense.fyi#52]
I'm trying to run the app locally, but I'm not sure how to set up my local environment so that I'm able to sign in and use the app. It would be helpful to add this to the ReadMe I think :D

**Comment by perryraskin** [comment]
It would also be helpful to explain how to set up `app.domain.com` on Vercel. Usually, you set a production domain, but how can we set production to be both `domain.com` and also `app.domain.com`?

**Comment by gokulkrishh** [comment]
@perryraskin Vercel does have it in their [docs](https://vercel.com/docs/concepts/projects/domains/add-a-domain). Have you check this out.

**Comment by perryraskin** [comment]
@gokulkrishh but what about running locally? I don't see an explanation on Vercel about locally setting this up

**Comment by gokulkrishh** [comment]
@perryraskin I followed some tutorials online to setup subdomain app.something. You can find the code in middleware.js file.
