### ISSUE TITLE
Supabase database triggers

### ISSUE THREAD

**Issue by marcojacobsNL** [gokulkrishh/expense.fyi#83]
Hey guys,

Awesome work on this code, it's nice and clean :)
I wanted to run this locally to test certain features and see how things work but I think i'm missing something in my Supabase environment. The user is never created, which makes me wonder if I miss some trigger or something in Supabase?
Is that correct? And if so, how can I add these :) ?

**Comment by gokulkrishh** [comment]
@marcojacobsNL Here is code snippet for [trigger function](https://github.com/gokulkrishh/expense.fyi/blob/main/prisma/functions/functions.sql) which insert the user info into the users table.
