### ISSUE TITLE
How to run the project locally

### ISSUE THREAD

**Issue by moonpatel** [gokulkrishh/expense.fyi#88]
I tried cloning the repository and did "npm install" and then "npm run dev". But it is stuck halfway. This is the log of my terminal, am I missing something?

`
> expense.fyi@0.1.0 predev
> prisma format && prisma generate

Prisma schema loaded from prisma\schema.prisma
Formatted C:\projects\open_source\expense.fyi\prisma\schema.prisma in 31ms 🚀
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (4.16.2 | library) to .\node_modules\@prisma\client in 123ms

✔ Generated field-level encryption migrations (1.4.5) to .\prisma\migrations in 20ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

> expense.fyi@0.1.0 dev
> next dev

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- event compiled client and server successfully in 243 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 198 ms (20 modules)
`

**Comment by gokulkrishh** [comment]
@moonpatel You need to add the API keys and supabase keys in .env file. Check env.example file for what you need to get it started.

**Comment by moonpatel** [comment]
> @moonpatel You need to add the API keys and supabase keys in .env file. Check env.example file for what you need to get it started.

How can I generate these enironment variables ?

**Comment by gokulkrishh** [comment]
@moonpatel You can get all the info the respective sites. `env.example` file has name for each required keys.

**Comment by dbhurley** [comment]
Please, how is this variable correctly set in the .env
`PRISMA_FIELD_ENCRYPTION_KEY`

**Comment by gokulkrishh** [comment]
@dbhurley you can follow the steps from [here](https://github.com/47ng/prisma-field-encryption?tab=readme-ov-file#2-setup-your-encryption-key).
