### ISSUE TITLE
Multi-currency selection

### ISSUE THREAD

**Issue by melvinsalas** [gokulkrishh/expense.fyi#9]
Some people often have expenses in different currencies, for example when they travel or live in a dual currency location or when they have online subscriptions in dollars.

Is it possible to add a currency selection to each expense, investment or subscription?

**Comment by gokulkrishh** [comment]
@melvinsalas Thats would be good feature to add. I would put it in upcoming roadmap. Thanks.

**Comment by melvinsalas** [comment]
It would be great to have access to the roadmap to try to help you in any way I can.

**Comment by gokulkrishh** [comment]
@melvinsalas Sure, its not open as of now as its messy, let me do some clean up and open it up for public.

**Comment by gokulkrishh** [comment]
@melvinsalas Lets try something new, i have created a poll for feature request here - https://github.com/gokulkrishh/expense.fyi/discussions/12

You can follow this and create one for multi currency or let me know i will create one. And take it forward.

**Comment by melvinsalas** [comment]
Closed because I opened this discussion: https://github.com/gokulkrishh/expense.fyi/discussions/13
