### ISSUE TITLE
sign in issue (in app.expense.fyi)

### ISSUE THREAD

**Issue by ammi1378** [gokulkrishh/expense.fyi#92]
I tried to login to site (app.expense.fyi) and it seems that login process is broken.

I don't know that i made a mistake or the issue exists globally. Magic link is not working.

**Comment by gokulkrishh** [comment]
@ammi1378 Thanks for reporting, can you share some specific about the issue and steps to re-produce?

**Comment by gokulkrishh** [comment]
Signin is working fine, so closing this issue
